### ISSUE TITLE
Dev Story: Refactoring

### ISSUE THREAD

**Issue by Serco627** [Serco627/workout-app#12]
# Refactor styled components
## Value Proposition

**As a developer**

**I want to** consolidate and centralize the styling for our application

**so that** the reusability and consistency of design components are improved. This will help make the codebase more maintainable and ensure a uniform design across the application.

## Acceptance criteria

- All styled Components are gathered in the styledComponents.js centralized file.

- Components are properly imported, adjusted and work as intended.

## Tasks

- [x] Create a `styledComponents.js` file that contains all commonly used Styled Components.

- [x] The file should include all components we created on our pages ( to ensure that we have a good overview)

- [x] Refactoring Pages:
  - [x] Home Page (HomePage): Import and use the centralized Styled Components from styles.js.
  - [x] Workouts List Page (WorkoutsList): Import and use the centralized Styled Components from styles.js.
  - [x] Exercise Details Page (ExerciseDetailsPage): Import and use the centralized Styled Components from styles.js.

  - [x] Verify that all relevant styles are correctly imported and applied.

**Comment by JohannMerck** [comment]
I´d suggest the following (small) ajdustments:

1. As a developer

I want a consolidated, centralized and unified file for all styled components used in our application, 

so that the reusability and consistency of design components are improved. This will help make the codebase more maintainable and ensure a uniform design across the application.

2. Tasks look fine

3. Add a short list of Acceptance Criteria, i.e.:

- [ ] All styled Components are gathered in the styledComponents.js centralized file. 
- [ ] Components are properly imported, adjusted and work as intended. 

General suggestion: depending on the used styles, consider using global Styles, in case you havent done so already anyway. Your overall styling looks terrific by the way 👍

**Comment by anapecic** [comment]
Fokus auf Styled Components

Bonus: Components auslagern (Workout Cards oder Exercises)
