### ISSUE TITLE
User Story: Use Local Storage State

### ISSUE THREAD

**Issue by anapecic** [Serco627/workout-app#18]
## Value proposition

**As a User**

**I want to**  keep my workots saved even when I refresh the page,

**So that I** don´t lose my progress or have to recreate my workout list every time I revisit the app.

## Description
Instead of using stats that store created or deleted workouts as along as a browser session is during, the local storage is installed

## Acceptance criteria
- [ ] Workouts created by the user are saved and remain available after a page refresh
- [ ] Deleted workouts remain deleted after a page refresh
- [ ] If there are no workouts, a message is displayed 'No workouts left? Go create  one and reach your goals!'
- [ ] The workout list updates in real-time to reflect any changes (creation or deletion) and persists these changes

## Tasks
- [ ] create a new branch 'local-storage-state'
- [ ] replace 'useState' code by using `localStorage` in the page 'workoutlist.js'
- [ ] import 'useLocalStorageStage' 
- [ ] control local storage where used with `console.log` with used variables
- [ ] control local storage with dev-tools inside Application/local Storage

**Comment by ahohnsen** [comment]
Hi!

What you’re aiming to achieve here is to ensure that the workouts are persisted and not lost after a page refresh. I would adjust the Value Proposition accordingly, and also the Acceptance Criteria, as they should not include technical details.

**Value Proposition**

As a user

I want to keep my workouts saved even when I refresh the page,

so that I don’t lose my progress or have to recreate my workout list every time I revisit the app.

**Acceptance Criteria**
- Workouts created by the user are saved and remain available after a page refresh.
- Deleted workouts remain deleted after a page refresh.
- If there are no workouts, a message is displayed: “No workouts left? Go create one and reach your goals!”
- The workout list updates in real-time to reflect any changes (creation or deletion) and persists these changes.


Hope, that helps. 🙂

**Comment by LorenzCoachK** [comment]
Hi Andrea,
thank for the precise feedback in this specific user story. I had some difficulties in finding the wording for this technic topic. Thanks a lot for your help! It shows me exactly what the benefit is from the users perspective.

Merci beaucoup! ☺️

**Comment by JohannMerck** [comment]
Description is a tad  grammatically confusing, otherwise all good :)
