### ISSUE TITLE
User Story: Header Re-Styling

### ISSUE THREAD

**Issue by anapecic** [Serco627/workout-app#24]
### User Story: Header Re-Styling

**Value Proposition:**  
As a **user**  
**I want** to see a clickable logo in the header
**In order to** navigate back to the homepage easily

**Description**
![Image](https://github.com/user-attachments/assets/63713517-ce69-4d2b-aa75-c8c102610451)

**Acceptance Criteria:**
1. The logo is visible in the header.
2. Clicking on the logo redirects the user to the homepage.
3. The User can see the Name and the slogan of the app in the header

**Tasks:**
- [x] create a new branch `header restyling`
- [x] Implement appname and slogan in the layout component in the header
- [x] Make the logo clickable, linking it to the homepage. `Link href....`
- [x] Style the header

**Comment by rvoll** [comment]
Looks good!
