### ISSUE TITLE
User Story: Re-Styling Fonts / Navigation

### ISSUE THREAD

**Issue by anapecic** [Serco627/workout-app#25]
## Value proposition

As a user
I want to use a visually appealing user interface
To be able to enjoy the feeling of a professional app

## Description

![Image](https://github.com/user-attachments/assets/50a86fd1-e512-4e25-b25d-941d92d33564)
![Image](https://github.com/user-attachments/assets/3834b8c2-169a-488b-860d-28fec3fb7068)

## Acceptance criteria
- [ ] The task is completed when the app is professionally designed and the team is satisfied
  - [ ] make a few adjustments to the design in several places in the app. For example, change the look of the headlines from deep black to anthracite, etc.
  - [ ] add a few optical effects to the navigation so that it stands out more from the content when scrolling
  - [ ] convert the workout-details-table from 3-lines to one line

## Tasks
- [ ] Create a Branch styling "fonts-nav-restyling"
- [ ] Restyle the headlines
- [ ] Restyle the Navbar
- [ ] Restyle the workout-details-list under the >show more< button
