### ISSUE TITLE
User Story: Re-Styling Muscle Groups

### ISSUE THREAD

**Issue by anapecic** [Serco627/workout-app#26]
## Value proposition

**As a user**
**I want to** easy see at each exercise any musclegroup that is in the spotlight
**In order to** be sure to choose the best exercise for the day.

## Description

![Image](https://github.com/user-attachments/assets/86e243a2-812e-42ac-856f-1784704e1983)

## Acceptance criteria
- [ ] show the musclegroups right below the title of the exercise
- [ ] highlight the musclegroups with state-of-the-Art styling

## Tasks
- [ ] create a feature branch 'restyle-musclegroups'
- [ ] re-arrange in 'exercises/ [id].js rendering of 'MuscleGroupList and move it between 'StyledExerciseName' and 'ExerciseDetailImage'
- [ ] make sure, the 'UL' brakes the line, if there are more than 3 'musclegroups'
- [ ] center all musclegroups correctly into the 'Container'-Styled-Component
- [ ] find a freaking-out styling for the musclegroups Elements

**Comment by rvoll** [comment]
Looks good! 
One comment: "make sure, the 'UL' brakes the line, if there are more than 3 'musclegroups'"
Could this possibly be done with flexbox or grid instead of UL?

**Comment by LorenzCoachK** [comment]
No Exercise has mire than 3 musclegroups. No felxboxes neccessary :-D
