### ISSUE TITLE
User Story: Crusher of the Day

### ISSUE THREAD

**Issue by anapecic** [Serco627/workout-app#27]
## Value proposition
**As a** gym app user
**I want to** view and access a daily workout called "Crusher of the Day"
**In order to** stay motivated, view targeted muscle groups, and seamlessly navigate to the workouts page for a detailed guide.

## Description
![Image](https://github.com/user-attachments/assets/27033036-0426-47ab-9014-98c5600a9cd3)

## Acceptance criteria
- Show a random workout per day from the default workouts.
- Add a description about the workout that explains why it is beneficial.
- Only show the beginning of the description and make it expandable by clicking "Show More".
- When no workout is available for the day, display a message: "No Crusher of the Day available."
- Clicking the workout card should redirect to the workoutlist
- Clicking "Show more" should expand the description without navigating away.

## Tasks
- [x] create feature branch daily-crusher
- [x] Implement the "Crusher of the Day" workout display and logic to show the workouts
- [x] Add click functionality for navigating to the workout details page.
- [x] Create functionality to expand/collapse the description when "Show more" is clicked.

**Comment by anapecic** [comment]
```
export const workouts = [
  {
    id: "1",
    name: "Full Body Workout",
    title: "Full Body Workout: Ignite Your Strength",
    description: `Get ready to ignite every muscle in your body with this intense Full Body Blast workout! This session is designed to challenge your endurance, power, and mental resilience. It’s time to sweat and sculpt from head to toe with a combination of strength-building and fat-torching movements. 

    Expect to hit all the major muscle groups: squats to build your foundation, push-ups to pump up your upper body, deadlifts to power through your lower back and hamstrings, and pull-ups to test your back and biceps. Each exercise demands focus, each set pushes your limits, and every rep brings you closer to your goals.

    Feel the burn, embrace the struggle, and watch as your body transforms into a machine of power and grace. No half measures here—this is where you find out what you’re made of. Ready to unleash your strength? Let's make it happen!`,
    exercises: [
      { exerciseId: "1", sets: 3, reps: 15 },
      { exerciseId: "2", sets: 3, reps: 12 },
      { exerciseId: "6", sets: 3, reps: 10 },
      { exerciseId: "10", sets: 3, reps: 8 },
      { exerciseId: "17", sets: 3, reps: 10 },
    ],
  },
  {
    id: "2",
    name: "Upper Body Workout",
    title: "Upper Body Workout: Build Like a Warrior",
    description: `Gear up for a powerful upper body session designed to make you stronger, faster, and ready to conquer anything. This workout targets your chest, shoulders, arms, and back with precision, giving you the lean, defined look you’re striving for. 

    You’ll push, pull, and press through challenging movements like push-ups, bench presses, and shoulder presses. Feel the burn in every rep as you build unstoppable strength. Let each set fuel your confidence and bring out the warrior within you.

    This is more than just a workout; it’s a test of your resolve, a way to sculpt your body and elevate your mindset. Every rep is a step toward becoming your strongest, most powerful self. Let’s get after it and build a body that reflects your determination!`,
    exercises: [
      { exerciseId: "1", sets: 4, reps: 12 },
      { exerciseId: "4", sets: 4, reps: 10 },
      { exerciseId: "7", sets: 4, reps: 8 },
      { exerciseId: "8", sets: 4, reps: 10 },
      { exerciseId: "10", sets: 4, reps: 6 },
    ],
  },
  {
    id: "3",
    name: "Lower Body Workout",
    title: "Lower Body Workout: Strengthen Your Foundation",
    description: `Strength begins from the ground up, and this Lower Body Power workout is designed to build your base. Power through squats, lunges, and deadlifts to target your legs, glutes, and core. 

    Your lower body is your foundation, and with each movement, you’ll feel yourself getting more stable, stronger, and ready for anything. We’re talking about deep squats that challenge your quads and hamstrings, deadlifts that build glutes of steel, and calf raises that fine-tune every muscle. 

    Embrace the grind—this is how you create lasting strength and balance. Whether you’re running, jumping, or lifting, this workout will ensure your legs can handle it all. Let’s go crush those lower body goals!`,
    exercises: [
      { exerciseId: "2", sets: 4, reps: 15 },
      { exerciseId: "5", sets: 4, reps: 12 },
      { exerciseId: "6", sets: 4, reps: 10 },
      { exerciseId: "11", sets: 4, reps: 12 },
      { exerciseId: "13", sets: 4, reps: 15 },
    ],
  },
  {
    id: "4",
    name: "Core Workout",
    title: "Core Workout: Forge an Unbreakable Core",
    description: `Your core is the powerhouse of your body, and this workout is all about building strength that lasts. Forge a solid foundation with planks, crunches, and twists that target your abs, obliques, and lower back.

    A strong core isn’t just about aesthetics—it’s about stability, balance, and control in everything you do. Whether you're lifting, running, or simply moving through your day, a rock-solid core will help you move better and perform stronger.

    Get ready to feel the burn as you tighten and tone your midsection. Push past the discomfort because this is where your true strength lies. Strong core, strong body, strong mind. Let’s forge an unbreakable core together!`,
    exercises: [
      { exerciseId: "3", sets: 3, reps: 60 },
      { exerciseId: "12", sets: 3, reps: 20 },
      { exerciseId: "15", sets: 3, reps: 15 },
      { exerciseId: "18", sets: 3, reps: 20 },
      { exerciseId: "20", sets: 3, reps: 30 },
    ],
  },
  {
    id: "5",
    name: "Cardio and Strength Workout",
    title: "Cardio and Strength Workout: Elevate Your Game",
    description: `Ready to take your fitness to the next level? This Cardio and Strength workout is a high-energy session designed to burn fat, build muscle, and boost your cardiovascular endurance all at once. It’s the ultimate combo for those who want to be fast, strong, and unstoppable.

    Get your heart racing with burpees and mountain climbers, while also building strength with hammer curls and reverse flys. Your body will be working at maximum capacity, pushing your endurance to new heights while chiseling out muscle definition.

    Don’t settle for just strength or just cardio—you can have it all! This workout is about pushing your limits, building a body that’s as powerful as it is agile. Let’s elevate your game and leave it all on the mat!`,
    exercises: [
      { exerciseId: "9", sets: 4, reps: 12 },
      { exerciseId: "16", sets: 4, reps: 20 },
      { exerciseId: "14", sets: 4, reps: 15 },
      { exerciseId: "19", sets: 4, reps: 12 },
      { exerciseId: "17", sets: 4, reps: 10 },
    ],
  },
];

```
