### ISSUE TITLE
User Story: Workouts List

### ISSUE THREAD

**Issue by LorenzCoachK** [Serco627/workout-app#5]
# Workout List

Value Proposition
As a user

I want to browse a list of workouts,

so that I can discover new workout routines to follow.

## Description

![Image](https://github.com/user-attachments/assets/a44d3de1-90a3-46aa-a7dd-1d1791fedfa1)

## Acceptance Criteria

- There is a dedicated page for the workouts list.
- The workouts list page is accessible from the homepage via a link.
- The workouts list page includes a link back to the homepage.
- The page is headlined with its purpose.
- Each workout listing includes:
  - Workout name
  - Exercises with sets and reps
  - All muscle groups involved in the workout
- The list supports vertical scrolling to accommodate multiple entries.

## Tasks

- [x] Create feature branch `/workout-list`
- [x] Inspect and adapt the example data in the [assets folder](./assets/workout.json)
- [x] create on the top of view port a sticky headline #Choose today´s workout 
- [x] Create component `WorkoutList`with a mapping over `workouts.json` and joining `excercises.json` containing following data
  - [x]  `exercises.json datafield "musclegroups"
    - [x] make sure, that each `musclegroup` is listed only once in the list of `targetedMusclegroups` mit Hilfe der function `uniqueMusclegroups`
  - [x] `workouts.json datafield "sets"
  - [x] `workouts.json datafield "reps"   
  - [x] `exercises.json datafield "name"
 - [x] each workout should be rendered as a vertical scrollable list
 - [x] create (or use the) component  "back" Button and place it sticky at the top of the viewport
 - [x] implement functionality to show more (the exercises with sets and reps) with a toggle function

**Comment by LorenzCoachK** [comment]
finalised user story 3.
