### ISSUE TITLE
User Story: Create Workout

### ISSUE THREAD

**Issue by Serco627** [Serco627/workout-app#9]
# Create Workout

## Value Proposition

**As a user**

**I want to** create and store new workouts,

**so that** I can have a personalised workout plan that suits my fitness goals.

## Description

![Image](https://github.com/user-attachments/assets/42a7d819-0355-4416-9ca8-c2198ab2b163)

## Acceptance Criteria

- A form for adding workouts is displayed at the top of the workouts list page.
- The form is headlined with its purpose.
- The form comprises labeled fields for:
  - Workout name
  - Exercise name (dynamic form fields)
  - Exercise sets (dynamic form fields)
  - Exercise reps (dynamic form fields)
- The following fields are mandatory:
  - Workout name
  - Exercise name (at least one exercise must be added)
  - Exercise sets (minimum 1)
  - Exercise reps (minimum 1)
- The exercise is selected from the existing exercises list via a dropdown menu.
- The exercise dropdown must include a default option, "Please select an exercise", and necessitates a selection.
- Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need completion.
- Upon form submission, the new workout is added to the top of the workouts list.

## Tasks

- [ ] Create feature branch `feature/create-workout`
- [ ] Create a "WorkoutForm" Component wich renders the individual/personal Workout-exercise-list and the form for selecting the exercises:
  - [ ] form-head (Back-Button, Headline, Inputfield "Workout Name*")
  - [ ] form-main (dynamically rendered fieldsets of exercises, starting with at least one exercise-fieldset)
  - [ ] form-footer (The "* required" text and the Add- and Submit-Button)
- [ ] Create an "Exercise" Component which renders one single Form-Fieldset which contains the Exercise-Name, the sets and the reps
  - [ ] Implement HTML-native inputfield checking (required fields), to validate if all fields are filled out
